package com.balestocks.scrap.domain.enums;

public enum StockEnum {
    HAPV3("Hapvida"),
    PETR4("Petrobras"),
    ABEV3("Ambev"),
    COGN3("Cogna"),
    B3SA3("B3"),
    LREN3("Lojas Renner"),
    BBAS3("Banco do Brasil"),
    CIEL3("Cielo"),
    BBDC4("Banco Bradesco"),
    ITUB4("Itaú Unibanco"),
    VALE3("Vale"),
    MGLU3("Magazine Luiza"),
    AMER3("Americanas"),
    GOLL4("GOL"),
    CPLE3("Copel"),
    ITSA4("Itaúsa"),
    PETR3("Petrobras"),
    AZUL4("Azul"),
    PCAR3("Grupo Pão de Açúcar"),
    RAIZ4("Raízen"),
    SOMA3("Grupo Soma"),
    CVCB3("CVC"),
    CPLE6("Copel"),
    PETZ3("Petz"),
    TIMS3("TIM"),
    RAIL3("Rumo"),
    MRVE3("MRV"),
    JBSS3("JBS"),
    CMIN3("CSN Mineração"),
    USIM5("Usiminas"),
    EQTL3("Equatorial Energia"),
    HBSA3("Hidrovias do Brasil"),
    BRFS3("BRF"),
    CMIG4("CEMIG"),
    GGBR4("Gerdau"),
    RENT3("Localiza"),
    CSAN3("Cosan"),
    SEQL3("Sequoia Logística"),
    ASAI3("Assaí"),
    CCRO3("Grupo CCR"),
    LWSA3("Locaweb"),
    NTCO3("Natura"),
    PRIO3("PetroRio"),
    ALOS3("Allos"),
    MULT3("Multiplan"),
    YDUQ3("YDUQS"),
    CYRE3("Cyrela"),
    CXSE3("Caixa Seguridade"),
    ANIM3("Ânima Educação"),
    HYPE3("Hypera"),
    RDOR3("Rede D'Or"),
    VBBR3("Vibra Energia"),
    GOAU4("Metalúrgica Gerdau"),
    ELET3("Eletrobras"),
    RCSL3("Recrusul"),
    EMBR3("Embraer"),
    SUZB3("Suzano"),
    BBSE3("BB Seguridade"),
    MRFG3("Marfrig"),
    MOVI3("Movida"),
    RADL3("RaiaDrogasil"),
    BBDC3("Banco Bradesco"),
    ONCO3("Oncoclínicas"),
    ENEV3("Eneva"),
    VAMO3("Grupo Vamos"),
    CSNA3("Siderúrgica Nacional"),
    IFCM3("Infracommerce"),
    BEEF3("Minerva"),
    AURE3("Auren Energia"),
    WEGE3("WEG"),
    AESB3("AES Brasil"),
    POMO4("Marcopolo"),
    CBAV3("CBA"),
    CRFB3("Carrefour Brasil"),
    SBSP3("Sabesp"),
    TOTS3("Totvs"),
    OIBR3("Oi"),
    BRAP4("Bradespar"),
    CEAB3("C&A"),
    GGPS3("GPS"),
    GFSA3("Gafisa"),
    RRRP3("3R Petroleum"),
    TRPL4("Transmissão Paulista"),
    UGPA3("Ultrapar"),
    FLRY3("Fleury"),
    SMFT3("Smart Fit"),
    SIMH3("Simpar"),
    CLSA3("ClearSale"),
    BRKM5("Braskem"),
    AZEV4("Azevedo & Travassos"),
    MTRE3("Mitre Realty"),
    VIVT3("Vivo"),
    RCSL4("Recrusul"),
    JHSF3("JHSF"),
    BHIA3("Casas Bahia"),
    AMBP3("Ambipar"),
    PDGR3("PDG Realty"),
    ENAT3("Enauta"),
    QUAL3("Qualicorp"),
    SRNA3("Serena Energia"),
    DXCO3("Dexco"),
    MLAS3("Multilaser"),
    TEND3("Construtora Tenda"),
    LJQQ3("Lojas Quero-Quero"),
    ECOR3("EcoRodovias"),
    STBP3("Santos Brasil"),
    GUAR3("Guararapes"),
    ELET6("Eletrobras"),
    VIVA3("Vivara"),
    DIRR3("Direcional"),
    IRBR3("IRB Brasil RE"),
    ARZZ3("Arezzo"),
    ENJU3("Enjoei"),
    DASA3("Dasa"),
    PSSA3("Porto Seguro"),
    SLCE3("SLC Agrícola"),
    RAPT4("Randon"),
    GMAT3("Grupo Mateus"),
    ALPA4("Alpargatas"),
    SMTO3("São Martinho"),
    ODPV3("Odontoprev"),
    KRSA3("Kora Saúde"),
    VVEO3("Viveo"),
    EZTC3("EZTEC"),
    ZAMP3("Zamp"),
    LIGT3("Light"),
    CPFE3("CPFL Energia"),
    MYPK3("Iochpe-Maxion"),
    CASH3("Méliuz"),
    SBFG3("Grupo SBF"),
    RECV3("PetroRecôncavo"),
    EGIE3("Engie"),
    CURY3("Cury"),
    BPAN4("Banco Pan"),
    CSMG3("COPASA"),
    SGPS3("Springs"),
    PLPL3("Plano&Plano"),
    POSI3("Positivo"),
    BRSR6("Banrisul"),
    MATD3("Mater Dei"),
    SEER3("Ser Educacional"),
    MILS3("Mills"),
    KLBN4("Klabin"),
    BRIT3("Brisanet"),
    MEAL3("IMC Alimentação"),
    TRIS3("Trisul"),
    SAPR4("Sanepar"),
    EVEN3("Even"),
    RANI3("Irani"),
    PORT3("Wilson Sons"),
    HBRE3("HBR Realty"),
    PGMN3("Pague Menos"),
    ESPA3("Espaçolaser"),
    TTEN3("3tentos"),
    MELK3("Melnick"),
    TASA4("Taurus"),
    TUPY3("Tupy"),
    GRND3("Grendene"),
    LAVV3("Lavvi Incorporadora"),
    TRAD3("Traders Club"),
    BMGB4("Banco BMG"),
    KEPL3("Kepler Weber"),
    MDIA3("M. Dias Branco"),
    NGRD3("Neogrid"),
    VULC3("Vulcabras"),
    ARML3("Armac"),
    ABCB4("Banco ABC Brasil"),
    INTB3("Intelbras"),
    JALL3("Jalles Machado"),
    CAML3("Camil Alimentos"),
    AZEV3("Azevedo & Travassos"),
    PTBL3("Portobello"),
    FESA4("Ferbasa"),
    ORVR3("Orizon"),
    CSED3("Cruzeiro do Sul Educacional"),
    VLID3("Valid"),
    USIM3("Usiminas"),
    POMO3("Marcopolo"),
    LEVE3("Mahle Metal Leve"),
    NEOE3("Neoenergia"),
    CMIG3("CEMIG"),
    AERI3("Aeris Energy"),
    VITT3("Vittia"),
    OPCT3("OceanPact"),
    JSLG3("JSL"),
    AGXY3("AgroGalaxy"),
    PINE4("Banco Pine"),
    SHUL4("Schulz"),
    BMOB3("Bemobi"),
    PRNR3("Priner"),
    ITUB3("Itaú Unibanco"),
    SHOW3("Time For Fun"),
    HBOR3("Helbor"),
    ETER3("Eternit"),
    DESK3("Desktop"),
    AMAR3("Lojas Marisa"),
    MDNE3("Moura Dubeux"),
    WIZC3("Wiz Soluções"),
    FIQE3("Unifique"),
    RPMG3("Refinaria de Manguinhos"),
    ROMI3("Indústrias ROMI"),
    PNVL3("Dimed"),
    BIOM3("Biomm"),
    KLBN3("Klabin"),
    FRAS3("Fras-le"),
    BLAU3("Blau Farmacêutica"),
    UNIP6("Unipar"),
    LOGG3("LOG CP"),
    SOJA3("Boa Safra Sementes"),
    TAEE4("Taesa"),
    PFRM3("Profarma"),
    DMVF3("D1000 Varejo Farma"),
    MBLY3("Mobly"),
    SYNE3("SYN"),
    TGMA3("Tegma"),
    TFCO4("Track & Field"),
    SAPR3("Sanepar"),
    RNEW4("Renova Energia"),
    INEP3("Inepar"),
    TCSA3("Tecnisa"),
    AGRO3("BrasilAgro"),
    TECN3("Technos"),
    ALLD3("Allied"),
    DEXP3("Dexxos"),
    LUPA3("Lupatech"),
    BRAP3("Bradespar"),
    TAEE3("Taesa"),
    SANB3("Banco Santander"),
    EUCA4("Eucatex"),
    INEP4("Inepar"),
    ELMD3("Eletromidia"),
    SANB4("Banco Santander"),
    PMAM3("Paranapanema"),
    LAND3("Terra Santa"),
    RNEW3("Renova Energia"),
    ALPK3("Estapar"),
    CAMB3("Cambuci"),
    VIVR3("Viver"),
    GGBR3("Gerdau"),
    UCAS3("Unicasa"),
    ITSA3("Itaúsa"),
    RAPT3("Randon"),
    JFEN3("João Fortes"),
    WEST3("Westwing"),
    CSUD3("CSU Cardsystem"),
    IGTI3("Iguatemi"),
    LPSB3("Lopes"),
    TPIS3("Triunfo"),
    CTNM4("Coteminas"),
    NINJ3("GetNinjas"),
    PDTC3("Padtec"),
    LOGN3("Log-In"),
    PTNT4("Pettenati"),
    GOAU3("Metalúrgica Gerdau"),
    NUTR3("Nutriplant"),
    BOBR4("Bombril"),
    HAGA4("Haga"),
    LVTC3("WDC Networks"),
    ENGI3("Energisa"),
    OIBR4("Oi"),
    UNIP3("Unipar"),
    BRKM3("Braskem"),
    ATOM3("ATOM"),
    COCE5("Coelce"),
    AALR3("Alliança"),
    VSTE3("LE LIS BLANC"),
    RSID3("Rossi Residencial"),
    SCAR3("São Carlos"),
    BMEB4("Banco Mercantil do Brasil"),
    HOOT4("Hotéis Othon"),
    BEES3("Banestes"),
    NEXP3("Brasil Brokers"),
    ALUP4("Alupar"),
    RDNI3("RNI"),
    ATMP3("Atma"),
    EQPA3("Equatorial Energia Pará"),
    TASA3("Taurus"),
    DOTZ3("Dotz"),
    EALT4("Electro Aço Altona"),
    CTSA4("Santanense"),
    OFSA3("Ourofino Saúde Animal"),
    CEBR6("CEB"),
    EMAE4("EMAE"),
    BRSR3("Banrisul"),
    CEBR5("CEB"),
    FHER3("Fertilizantes Heringer"),
    TRPL3("Transmissão Paulista"),
    ENGI4("Energisa"),
    TELB4("Telebras"),
    MTSA4("Metisa"),
    BAZA3("Banco da Amazônia"),
    CGRA3("Grazziotin"),
    FRIO3("Metalfrio"),
    CGRA4("Grazziotin"),
    BEES4("Banestes"),
    BAHI3("Bahema"),
    ALUP3("Alupar"),
    SNSY5("Sansuy"),
    OSXB3("OSX Brasil"),
    SNSY3("Sansuy"),
    BPAC5("Banco BTG Pactual"),
    WHRL4("Whirlpool"),
    BPAC3("Banco BTG Pactual"),
    CEBR3("CEB"),
    EPAR3("Embpar Participações"),
    ALPA3("Alpargatas"),
    MNPR3("Minupar"),
    NORD3("Nordon"),
    GOLL11("GOL"),
    CGAS5("Comgás"),
    APER3("Alper"),
    MNDL3("Mundial"),
    CRPG5("Tronox Pigmentos"),
    REDE3("Rede Energia"),
    CEDO4("Cedro Têxtil"),
    DEXP4("Dexxos"),
    FIEI3("Fica"),
    CLSC4("Celesc"),
    EKTR4("Elektro"),
    GEPA4("Rio Paranapanema Energia"),
    TELB3("Telebras"),
    EALT3("Electro Aço Altona"),
    BSLI4("Banco de Brasília"),
    BSLI3("Banco de Brasília"),
    RSUL4("Metalúrgica Riosulense"),
    BMIN4("Banco Mercantil de Investimentos"),
    PTNT3("Pettenati"),
    WLMM4("WLM"),
    CEDO3("Cedro Têxtil"),
    CRPG6("Tronox Pigmentos"),
    CSRN5("COSERN"),
    CTNM3("Coteminas"),
    WHRL3("Whirlpool"),
    HAGA3("Haga"),
    AZEV11("Azevedo & Travassos"),
    BAUH4("Excelsior"),
    CLSC3("Celesc"),
    BGIP4("Banese"),
    IGTI4("Iguatemi"),
    RPAD5("Alfa Holdings"),
    PINE3("Banco Pine"),
    CTSA3("Santanense"),
    UNIP5("Unipar"),
    GEPA3("Rio Paranapanema Energia"),
    BMEB3("Banco Mercantil do Brasil"),
    CSRN6("COSERN"),
    JOPA3("Josapar"),
    CTKA4("Karsten"),
    LUXM4("Trevisa"),
    MGEL4("Mangels"),
    BALM4("Baumer"),
    MWET3("Wetzel"),
    MAPT4("Cemepe"),
    BMKS3("Monark"),
    DOHL4("Döhler"),
    MWET4("Wetzel"),
    PLAS3("Plascar"),
    MRSA3B("MRS Logística"),
    AVLL3("Alphaville"),
    CSRN3("COSERN"),
    HETA4("Hercules"),
    PSVM11("PSVM11"),
    PEAB4("Participações Aliança da Bahia"),
    BNBR3("Banco do Nordeste"),
    AFLT3("Afluente T"),
    HBTS5("Habitasul"),
    CEEB3("COELBA"),
    COCE3("Coelce"),
    BGIP3("Banese"),
    EUCA3("Eucatex"),
    FESA3("Ferbasa"),
    BDLL4("Bardella"),
    TEKA4("Teka"),
    EQMA3B("Equatorial Maranhão"),
    BALM3("Baumer"),
    ESTR4("Estrela"),
    MERC4("Mercantil do Brasil Financeira"),
    PEAB3("Participações Aliança da Bahia"),
    MOAR3("Monteiro Aranha"),
    EKTR3("Elektro"),
    AHEB3("São Paulo Turismo"),
    BRKM6("Braskem"),
    RPAD3("Alfa Holdings"),
    RPAD6("Alfa Holdings"),
    MAPT3("Cemepe"),
    CGAS3("Comgás"),
    LIPR3("Eletropar"),
    WLMM3("WLM"),
    BRSR5("Banrisul"),
    PINE11("Banco Pine"),
    CBEE3("Ampla Energia"),
    CTKA3("Karsten"),
    EQPA6("Equatorial Energia Pará"),
    DOHL3("Döhler"),
    GSHP3("General Shopping & Outlets"),
    TKNO4("Tekno"),
    PATI3("Panatlântica"),
    USIM6("Usiminas"),
    JOPA4("Josapar"),
    DTCY3("Dtcom");

    private final String companyName;

    StockEnum(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public static StockEnum fromCode(String code) {
        for (StockEnum stockCode : StockEnum.values()) {
            if (stockCode.name().equalsIgnoreCase(code)) {
                return stockCode;
            }
        }
        throw new IllegalArgumentException("Unknown stock code: " + code);
    }
}
